### ISSUE TITLE
[Umbrella] Roadmap

### ISSUE THREAD

**Issue by raibima** [traveloka/react-accio#11]
### Short term (patch & minor releases)
- [ ] Expose `preload` method as one of render prop arguments
- [ ] Update `trigger` documentation (`trigger` can now be invoked using ref)
- [ ] Allow resolver injection from props (#9)

### Long term (major release)
- [ ] Explore suspense (do we still need react-accio when suspense has been released?)
- [ ] Decide what to do with SSR (currently lack of explicit SSR render prop state)
